# Jekyll configuration file

collections:
  mathblogs:
    output: true
    permalink: /blogs/math/:name.html
  physicsblogs:
    output: true
    permalink: /blogs/physics/:name.html
  aiblogs:
    output: true
    permalink: /blogs/ai/:name.html

# Set the markdown processor
markdown: kramdown

# Site settings (customize as needed)
title: Sai Sanjay's Website
