# Jekyll configuration file

collections:
  mathblogs:
    output: true
    permalink: /blogs/math-blogs/:name.html

# Set the markdown processor
markdown: kramdown

# Site settings (customize as needed)
title: Sai Sanjay's Website
